export enum Measurements {
  cup = "cup",
  teaspoon = "teaspoon",
  tablespoon = "tablespoon",
  bunch = "bunch",
  dash = "dash",
  drop = "drop",
  gram = "gram",
  kilogram = "kilogram",
  handful = "handful",
  milliliter = "milliliter",
  liter = "liter",
  splash = "splash",
  shot = "shot",
  pound = "pound",
  pinch = "pinch",
  packet = "packet",
  ounce = "ounce",
}
